name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install zerotier
      run: curl -s https://install.zerotier.com | sudo bash

    - name: Test
      run: go test -v ./...
